# Clase 1 Python for Professionals

## An Introduction to Python

# Tema 1 (Variables)

#### Las variables son elementos utilizados en python para guardar resultados que deseamos utilizar posteriormente para realizar alguna tarea con estos

#### Las variables no pueden contener espacios al momento de crearse

### Tipos de datos

##### 1. Númericos

In [ ]:
## Variables numericas
a = 10 ## Tipo Int
b = 2.5 ## Tipo Float
edad = 15

In [ ]:
print(type(edad) == "edad")
print(type("edad"))

False
<class 'str'>
15


In [ ]:
## Verificar que realmente las letras contengan los valores indicados y verificar el tipo de dato
print(a)
print(type(b))
print(type(edad))

10
<class 'float'>
<class 'int'>


In [ ]:
### Variable con espacios

edad_carlos = 15 ### Las variables deben siempre estar unidas por _ en caso de espacios
print(edad_carlos)

15


#### * Nota
#### El comando "print" es una palabra reservada que se utiliza para desplegar el resultado de alguna variable que se desee observar


In [ ]:
## Palabras reservadas

## int, float, str, for, while, lambda, in, and, or, import, install, pip

#### 2.Texto

In [ ]:
## Variables de texto
nombre = 'Alexander'
apellido = "Valverde"
nombre_completo = f'Mi nombre es {nombre} {apellido}'
nombre_completo_2 =  "Mi nombre es" + " " + nombre + " " + apellido
print(nombre_completo_2)

Mi nombre es Alexander Valverde


In [ ]:
## Verificar que realmente las letras contengan los valores indicados y verificar el tipo de dato
print(nombre)
print(apellido)
print(type(apellido))
print(type(nombre_completo))
print(nombre_completo)

Alexander
Valverde
<class 'str'>
<class 'str'>
Mi nombre es Alexander Valverde


#### 3.Booleano (True & False)

In [ ]:
## Variables Booleanas

Verdadero = True # Para que una variable contenga el resultado de (Verdadero) debe ser igual a 'True' no "TRUE","Verdadero","verdadero", etc.
Falso = False # Para que una variable contenga el resultado de (Falso) debe ser igual a 'False' no "FALSE","Falso","falso", etc.

In [ ]:
print(Verdadero)
print(Falso)
print(type(Verdadero))

True
False
<class 'bool'>


In [ ]:
## Ejemplo

comparacion_numerica = 2 == 2
comparacion_texto = "Carlos" == "Pedros"
comparacion_texto_longitud = len("Carlo") == len("Pedro")

In [ ]:
print(comparacion_numerica)
print(comparacion_texto)
print(comparacion_texto_longitud)
print(len("Carlo"))

True
False
True
5


#### 4.Fecha

In [ ]:
## Variables fecha
import datetime
from datetime import date

fecha_cumpleaños = 17/10/2001
fecha_cumpleaños_true = date(2001, 10, 17)

In [ ]:
print(fecha_cumpleaños)
print(fecha_cumpleaños_true)
print(type(fecha_cumpleaños_true))
print(type(fecha_cumpleaños))

0.000849575212393803
2001-10-17
<class 'datetime.date'>
<class 'float'>


### Ejemplos

In [ ]:
# Sumas - Restas - Multiplicacion - Division

suma = a + b
resta = b - a
multiplicacion = a * 200
division = b / 5.2

print(suma)
print(resta)
print(multiplicacion)
print(division)

12.5
-7.5
2000
0.4807692307692307


In [ ]:
# Ejemplo completo

edad = str((date.today() - fecha_cumpleaños_true) / 365)
print(edad)
print("La edad de Alexander es de {} años".format(edad[0:2]))

if edad[0:2] == '21':
    booleano = True
else:
    booleano = False
print(booleano)

21 days, 21:06:24.657534
La edad de Alexander es de 21 años
True


## Tipos de datos intermedios

#### 1. Listas

##### Una lista en programación es una estructura de datos que se utiliza para almacenar y organizar colecciones ordenadas de elementos

##### Caracteristicas:
###### - Sintaxis = []
###### - Mutables
###### - Iteracion
###### - Facil acceso
###### - Permite guardar elementos de diferentes tipos

In [20]:
## Ejemplo de listas

# Crear una lista de números
mi_lista = [15, 5, 20, 30, 40, 70]

print(mi_lista)
# Acceder a elementos por índice
primer_elemento = mi_lista[0]
grupos_elementos = mi_lista[1:4]

#print(primer_elemento)
#print(grupos_elementos)


# Modificar elementos
mi_lista[2] = 35

print(mi_lista)

# Agregar elementos al final
mi_lista.append(60)

print(mi_lista)

# Ordenar la lista
mi_lista.sort(reverse=True)

print(mi_lista)

# Eliminar un elemento por valor
mi_lista.remove(40)

print(mi_lista)

# Eliminar el último elemento
ultimo_elemento = mi_lista.pop()

print(mi_lista)


[15, 5, 20, 30, 40, 70]
[15, 5, 35, 30, 40, 70]
[15, 5, 35, 30, 40, 70, 60]
[70, 60, 40, 35, 30, 15, 5]
[70, 60, 35, 30, 15, 5]
[70, 60, 35, 30, 15]


In [ ]:
## Codigo prueba

#lista_1 = []

#for x in numeros:
  #lista_1.append(x)

In [24]:
## Ejemplo con texto

lista_texto = ['Carlos','Alex','Luisa',34,25,21]
primer_elemento = lista_texto[0]
ultimo_elemento = lista_texto[-1]
print(ultimo_elemento)
print(len(lista_texto))

21
6


#### 2. Diccionarios

##### Un diccionario es una estructura de datos fundamental en programación que permite almacenar y organizar datos en pares de clave-valor.

##### Caracteristicas:
###### - Sintaxis = {}
###### - Clave-valor
###### - Mutables
###### - Iteracion
###### - Facil acceso
###### - Permite guardar elementos de diferentes tipos

In [26]:
## Ejemplo de diccionarios

# Crear un diccionario de información de una persona
persona = {
    "nombre": "Juan",
    "edad": 22,
    "ciudad": "San Jose",
    "email": "juan@example.com"
}

# Acceder a valores por clave
nombre = persona["nombre"]
edad = persona["edad"]
print(persona)

# Modificar un valor
persona["edad"] = 31
print(persona["edad"])

# Agregar un nuevo par clave-valor
persona["ocupacion"] = "Economista"
print(persona)

# Eliminar un par clave-valor
del persona["email"]

print(persona)


{'nombre': 'Juan', 'edad': 22, 'ciudad': 'San Jose', 'email': 'juan@example.com'}
31
{'nombre': 'Juan', 'edad': 31, 'ciudad': 'San Jose', 'email': 'juan@example.com', 'ocupacion': 'Economista'}
{'nombre': 'Juan', 'edad': 31, 'ciudad': 'San Jose', 'ocupacion': 'Economista'}


In [27]:
for clave, valor in persona.items():
  print(f'{clave}:{valor}')

nombre:Juan
edad:31
ciudad:San Jose
ocupacion:Economista


#### 3. Tuples

##### Un tuple es una estructura de datos que se utiliza para almacenar un conjunto de valores relacionados que no cambiarán, como coordenadas geográficas, datos constantes o estructuras de datos para las cuales no se prevén modificaciones.

##### Caracteristicas:
###### - Sintaxis = ()
###### - Inmutables
###### - Mayor eficiencia computacional
###### - Mas rapidas que las listas/diccionarios

In [34]:
## Ejemplos tupla

# Crear una tupla
mi_tupla = (10, 20, 30, 40, 50)

# Acceder a elementos por índice
primer_elemento = mi_tupla[0]  # 10
segundo_elemento = mi_tupla[1]  # 20

print(primer_elemento)
# Concatenar tuplas
otra_tupla = (60, 70)
concatenada = mi_tupla + otra_tupla

# Encontrar la longitud de la tupla
longitud = len(mi_tupla)  # 5
print(longitud)

# Probar inmutabilidad

#mi_tupla[0] = 30

print(mi_tupla)
print(concatenada)


10
5
(10, 20, 30, 40, 50)
(10, 20, 30, 40, 50, 60, 70)


In [37]:
## Tuplas de texto

frutas = ("manzana","pera","uva")
for fruta in frutas:
  print(fruta)

frutas_lista = ["manzana", "pera","uva"]
for fruit in frutas_lista:
  print(fruit)

manzana
pera
uva
manzana
pera
uva


### Tipos de datos avanzados

#### 1. Arrays

#### Los arrays son estructuras de datos fundamentales para almacenar y operar con datos numéricos en forma de matrices multidimensionales.

##### Caracteristicas:
###### - Homogeneo
###### - Indices numericos
###### - Multidimensionalidad
###### - Mas rapidas que las listas/diccionarios/tuples
###### - Uso numérico



In [38]:
## Variable Arrays

import numpy as np

# Crear un ndarray
numeros = np.array([10, 20, 30, 40, 50])

# Acceder a elementos por índice
primer_elemento = numeros[0]  # 10
segundo_elemento = numeros[1]  # 20

print(primer_elemento)

# Realizar operaciones vectorizadas
doble = numeros * 2
suma = numeros + 5

# Crear un ndarray tridimensional (matriz)
matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Acceder a elementos de la matriz
elemento = matriz[1, 2]  # 6

# Realizar operaciones matriciales
producto = np.dot(matriz, matriz)

print(numeros)
print(doble)
print(suma)
print(matriz)
print(producto)

10
[10 20 30 40 50]
[ 20  40  60  80 100]
[15 25 35 45 55]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
